name: "William Heng" # Name for site
permalink: /:year/:month/:title # Permalink for site
url: http://192.168.1.12:4000/ # URL to site
analytics: # Google analytics tracking code

header: # Header
  text: "WRITE" # Header text, looks better in all-caps IMO
  subtext: "Stories worth writing." # Header subtext

author:
  use: true # Author display being used
  picture-url: "http://local.dev/template/circle-me.png" # Relative URL to your picture in 150px x 150px
  name: "William Heng" # Your name
  about: "about" # Relative URL link to 'About me' page e.g. "picture.html" if it's http://localhost/picture.html
  twitter: "william8th" # Twitter username
  github: "william8th" # Github username

markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "/page/:num"
